### PR TITLE
Shared/static libraries support

### PR DESCRIPTION
**Pull request by bplaa-yai**
This PR separates the main unionfs logic from fuse op handlers, in order to be able to produce a library version of unionfs. This does not provide a proper api and all symbols are exported, but it makes it possible to use unionfs with something like

```
#include "unionfs.h"
#include "opts.h"
...
uopt_init();
uopt.cow_enabled = true;
...
add_branch(...);
add_branch(...);
unionfs_post_opts();
...
fuse_main(...);
```

The resulting unionfs binary is statically linked against libunionfs.a.
The tests are ok, and the install rules are not changed.

### CODE REVIEW

**Comment by rpodgorny** [comment]
hi! thanks for the patches. i'll review then soon but can you, please, describe your exact use case? thank you...

**Comment by bplaa-yai** [comment]
Hi Radek. Sure, the use case is a program that needs to mount/unmount multiple unionfs mount points. That could be achieved by forking/exec the unionfs process, but would provide poor integration (error checking, thread control and so on), so integrating unionfs as a library seems like a good alternative. This would also allow one to customize the fuse handlers, by replacing or wrapping unionfs handlers.
I understand there may not be a huge interest in this use case, that's why the patch is proposed with a minimal changeset in mind.
If there is interest in this use case, that would mean exposing a proper api, headers and documentation.

**Comment by rpodgorny** [comment]
hmmm, interesting. i actually like the idea! ...are you using it already in production somewhere?

@aakefbs: me too but that's another issue - this patch does not add any new globals (afaik).

**Comment by bplaa-yai** [comment]
It's not used in production yet, hopefully someday !

**Comment by rpodgorny** [comment]
well, i took me a year, but it's finally merged. thanks!

**Pull request merged**
