### PR TITLE
macos build stuff

### PR DESCRIPTION
**Pull request by rpodgorny**

### CODE REVIEW

**Comment by rpodgorny** [comment]
@WaterJuice could you please try to build with the latest version (with some macos stuff included)?

i'll merge any macos related patch you have, if you want to.

also, wouldn't it be better to create a brew bottle (or how it's called)?

**Comment by xabrouck** [comment]
Hi @rpodgorny ,

I'm not OP; I just tested your latest version and it works fine, but could you do this?:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index f9cd691..aab73c9 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -32,6 +32,7 @@ ELSE (WITH_XATTR)
 ENDIF (WITH_XATTR)

 if (UNIX AND APPLE)
+        option(WITH_LIBFUSE3 "Enable LibFUSE3 support" FALSE)
        find_library(MACFUSE_PATH fuse HINTS /usr/local/lib)
        get_filename_component(MACFUSE_DIRECTORY ${MACFUSE_PATH} DIRECTORY)
        link_directories(${MACFUSE_DIRECTORY})
```

so that macOS users don't need to `cmake . -DWITH_LIBFUSE3=FALSE` but just `cmake .`.

Thanks

**Comment by rpodgorny** [comment]
> Hi @rpodgorny ,
> 
> I'm not OP; I just tested your latest version and it works fine, but could you do this?:
> 
> ```diff
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index f9cd691..aab73c9 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -32,6 +32,7 @@ ELSE (WITH_XATTR)
>  ENDIF (WITH_XATTR)
> 
>  if (UNIX AND APPLE)
> +        option(WITH_LIBFUSE3 "Enable LibFUSE3 support" FALSE)
>         find_library(MACFUSE_PATH fuse HINTS /usr/local/lib)
>         get_filename_component(MACFUSE_DIRECTORY ${MACFUSE_PATH} DIRECTORY)
>         link_directories(${MACFUSE_DIRECTORY})
> ```
> 
> so that macOS users don't need to `cmake . -DWITH_LIBFUSE3=FALSE` but just `cmake .`.
> 
> Thanks

hi @xabrouck ! just to be sure:

 * is your patch against "master" or this merge request?
 * is there any problem with fuse3 on macos? or why should we default to fuse2 on macos?

thanks!

**Comment by bsbernd** [comment]
Hi Radek,

I'm working a bit on libfuse now - it does not support anything than Linux. I guess MacOS and BSD are using an older version, which is then libfuse2.

**Comment by xabrouck** [comment]
@rpodgorny , I'm using macFuse 4.5.0 (=latest) from https://github.com/osxfuse/osxfuse/releases.
The FUSE library version inside it is : `FUSE library version: 2.9.9`.
My patch and testing was done against master.

```
% git https://github.com/rpodgorny/unionfs-fuse test && cd test && cmake .
git: 'https://github.com/rpodgorny/unionfs-fuse' is not a git command. See 'git --help'.
xabrouck@M2MAX Documents % git clone https://github.com/rpodgorny/unionfs-fuse test && cd test && cmake .
Cloning into 'test'...
remote: Enumerating objects: 3468, done.
remote: Counting objects: 100% (493/493), done.
remote: Compressing objects: 100% (197/197), done.
remote: Total 3468 (delta 318), reused 419 (delta 294), pack-reused 2975
Receiving objects: 100% (3468/3468), 663.97 KiB | 7.06 MiB/s, done.
Resolving deltas: 100% (2282/2282), done.
-- The C compiler identification is AppleClang 15.0.0.15000040
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include file sys/xattr.h
-- Looking for include file sys/xattr.h - found
-- Looking for include file attr/xattr.h
-- Looking for include file attr/xattr.h - not found
-- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "0.29.2")
-- Checking for module 'fuse3'
--   No package 'fuse3' found
CMake Error at /opt/homebrew/Cellar/cmake/3.27.6/share/cmake/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.27.6/share/cmake/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  src/CMakeLists.txt:20 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
```

With the patch:

```
% git clone https://github.com/rpodgorny/unionfs-fuse test2 && cd test2 && patch -p1 && ../nofuse3.diff && cmake .
Cloning into 'test2'...
remote: Enumerating objects: 3468, done.
remote: Counting objects: 100% (493/493), done.
remote: Compressing objects: 100% (197/197), done.
remote: Total 3468 (delta 318), reused 419 (delta 294), pack-reused 2975
Receiving objects: 100% (3468/3468), 663.97 KiB | 7.06 MiB/s, done.
Resolving deltas: 100% (2282/2282), done.
^C%
xabrouck@M2MAX test2 % rm -Rf test2
xabrouck@M2MAX test2 % git clone https://github.com/rpodgorny/unionfs-fuse test2 && cd test2 && patch -p1 < ../nofuse3.diff && cmake .
Cloning into 'test2'...
remote: Enumerating objects: 3468, done.
remote: Counting objects: 100% (493/493), done.
remote: Compressing objects: 100% (197/197), done.
remote: Total 3468 (delta 318), reused 419 (delta 294), pack-reused 2975
Receiving objects: 100% (3468/3468), 663.97 KiB | 8.74 MiB/s, done.
Resolving deltas: 100% (2282/2282), done.
zsh: no such file or directory: ../nofuse3.diff
xabrouck@M2MAX test2 % cd ..
xabrouck@M2MAX test2 % ls *.diff
zsh: no matches found: *.diff
xabrouck@M2MAX test2 % cd ..
xabrouck@M2MAX Documents % rm -Rf test2
xabrouck@M2MAX Documents % git clone https://github.com/rpodgorny/unionfs-fuse test2 && cd test2 && patch -p1 < ../nofuse3.diff && cmake .
Cloning into 'test2'...
remote: Enumerating objects: 3468, done.
remote: Counting objects: 100% (493/493), done.
remote: Compressing objects: 100% (197/197), done.
remote: Total 3468 (delta 318), reused 419 (delta 294), pack-reused 2975
Receiving objects: 100% (3468/3468), 663.97 KiB | 1.92 MiB/s, done.
Resolving deltas: 100% (2282/2282), done.
patching file CMakeLists.txt
-- The C compiler identification is AppleClang 15.0.0.15000040
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include file sys/xattr.h
-- Looking for include file sys/xattr.h - found
-- Looking for include file attr/xattr.h
-- Looking for include file attr/xattr.h - not found
-- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "0.29.2")
-- Checking for module 'fuse'
--   Found fuse, version 2.9.9
-- Configuring done (0.4s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/xabrouck/Documents/test2
```

I believe the default is fuse2 on macOS.

**Comment by rpodgorny** [comment]
can you please try now with current master?

**Comment by xabrouck** [comment]
It works fine:

```
% git clone https://github.com/rpodgorny/unionfs-fuse test && cd test && cmake .
Cloning into 'test'...
remote: Enumerating objects: 3471, done.
remote: Counting objects: 100% (496/496), done.
remote: Compressing objects: 100% (198/198), done.
remote: Total 3471 (delta 320), reused 422 (delta 296), pack-reused 2975
Receiving objects: 100% (3471/3471), 664.34 KiB | 8.41 MiB/s, done.
Resolving deltas: 100% (2284/2284), done.
-- The C compiler identification is AppleClang 15.0.0.15000040
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include file sys/xattr.h
-- Looking for include file sys/xattr.h - found
-- Looking for include file attr/xattr.h
-- Looking for include file attr/xattr.h - not found
-- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "0.29.2")
-- Checking for module 'fuse'
--   Found fuse, version 2.9.9
-- Configuring done (0.4s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/xabrouck/Documents/test
```

Thank you.

**Comment by xabrouck** [comment]
Just an unrelated warning:
```
/Users/xabrouck/Documents/test/src/usyslog.c:170:17: warning: overlapping comparisons always evaluate to false [-Wtautological-overlap-compare]
        if (tinfo == 0 && tinfo == 1)
            ~~~~~~~~~~~^~~~~~~~~~~~~
1 warning generated.
```

**Comment by rpodgorny** [comment]
ok, thanks a lot! ...one more try (on current master), please?

**Comment by xabrouck** [comment]
Flawless:

```
% git clone https://github.com/rpodgorny/unionfs-fuse test && cd test && cmake . && make
Cloning into 'test'...
remote: Enumerating objects: 3479, done.
remote: Counting objects: 100% (504/504), done.
remote: Compressing objects: 100% (203/203), done.
remote: Total 3479 (delta 326), reused 427 (delta 299), pack-reused 2975
Receiving objects: 100% (3479/3479), 664.92 KiB | 857.00 KiB/s, done.
Resolving deltas: 100% (2290/2290), done.
-- The C compiler identification is AppleClang 15.0.0.15000040
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include file sys/xattr.h
-- Looking for include file sys/xattr.h - found
-- Looking for include file attr/xattr.h
-- Looking for include file attr/xattr.h - not found
-- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "0.29.2")
-- Checking for module 'fuse'
--   Found fuse, version 2.9.9
-- Configuring done (2.3s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/xabrouck/Documents/test
[  5%] Building C object src/CMakeFiles/unionfs.dir/unionfs.c.o
[ 11%] Building C object src/CMakeFiles/unionfs.dir/opts.c.o
[ 16%] Building C object src/CMakeFiles/unionfs.dir/debug.c.o
[ 22%] Building C object src/CMakeFiles/unionfs.dir/findbranch.c.o
[ 27%] Building C object src/CMakeFiles/unionfs.dir/readdir.c.o
[ 33%] Building C object src/CMakeFiles/unionfs.dir/general.c.o
[ 38%] Building C object src/CMakeFiles/unionfs.dir/unlink.c.o
[ 44%] Building C object src/CMakeFiles/unionfs.dir/cow.c.o
[ 50%] Building C object src/CMakeFiles/unionfs.dir/cow_utils.c.o
[ 55%] Building C object src/CMakeFiles/unionfs.dir/string.c.o
[ 61%] Building C object src/CMakeFiles/unionfs.dir/rmdir.c.o
[ 66%] Building C object src/CMakeFiles/unionfs.dir/usyslog.c.o
[ 72%] Building C object src/CMakeFiles/unionfs.dir/fuse_ops.c.o
[ 77%] Building C object src/CMakeFiles/unionfs.dir/hashtable.c.o
[ 83%] Building C object src/CMakeFiles/unionfs.dir/hashtable_itr.c.o
[ 88%] Linking C executable unionfs
[ 88%] Built target unionfs
[ 94%] Building C object src/CMakeFiles/unionfsctl.dir/unionfsctl.c.o
[100%] Linking C executable unionfsctl
[100%] Built target unionfsctl
```

**Comment by rpodgorny** [comment]
thanks a lot! ...i will tag a new version soon.

**Comment by rpodgorny** [comment]
since we now have some macos support in master i'm closing this pull request. everyone, feel free to open new one!

**Pull request closed without merging**
